name: Build Release Executables

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.9']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable
      run: |
        pyinstaller --onefile --name=repairpbc --distpath=./dist --clean --noconfirm --hidden-import=numpy --hidden-import=pandas --hidden-import=mdtraj --hidden-import=mdtraj.formats.xtc --hidden-import=mdtraj.formats.gro --hidden-import=mdtraj.formats.pdb --collect-all mdtraj --exclude-module matplotlib --exclude-module tkinter repair_pbc.py
        
    - name: Fix macOS permissions
      if: matrix.os == 'macos-latest'
      run: |
        xattr -cr ./dist/repairpbc
        chmod +x ./dist/repairpbc

    - name: Rename Windows executable
      if: matrix.os == 'windows-latest'
      shell: bash
      run: mv ./dist/repairpbc.exe ./dist/repairpbc-windows.exe

    - name: Rename macOS executable
      if: matrix.os == 'macos-latest'
      run: mv ./dist/repairpbc ./dist/repairpbc-macos

    - name: Rename Linux executable
      if: matrix.os == 'ubuntu-latest'
      run: mv ./dist/repairpbc ./dist/repairpbc-linux

    - name: Upload Windows executable
      if: matrix.os == 'windows-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/repairpbc-windows.exe
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload macOS executable
      if: matrix.os == 'macos-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/repairpbc-macos
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Linux executable
      if: matrix.os == 'ubuntu-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/repairpbc-linux
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}